basePath: /
definitions:
  models.Address:
    properties:
      city:
        type: string
      country:
        type: string
      line:
        type: string
      state:
        type: string
      user_id:
        type: integer
      zipcode:
        type: string
    type: object
  models.Skill:
    properties:
      status:
        type: integer
      title:
        type: string
    type: object
  models.User:
    properties:
      address:
        $ref: '#/definitions/models.Address'
        type: object
      email:
        type: string
      language:
        type: string
      password:
        type: string
      user_type:
        type: integer
      username:
        type: string
    type: object
host: localhost:3333
info:
  contact:
    email: dev.meireles@gmail.com
    name: API Support
  description: This is the NextJob API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: NextJob API
  version: "1.0"
paths:
  /skill:
    post:
      consumes:
      - application/json
      description: Create a new skill with the input
      parameters:
      - description: Create a skill
        in: body
        name: skill
        required: true
        schema:
          $ref: '#/definitions/models.Skill'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Skill'
      summary: Create a new skill
      tags:
      - skills
  /skill/{id}:
    delete:
      consumes:
      - application/json
      description: Delete the skill corresponding to the input id
      parameters:
      - description: ID of the skill to be deleted
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete skill identified by the given id
      tags:
      - skills
    get:
      consumes:
      - application/json
      description: Get details of skill corresponding to the input id
      parameters:
      - description: ID of the skill
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Skill'
      summary: Get details for a given skill id
      tags:
      - skills
    put:
      consumes:
      - application/json
      description: Update the skill corresponding to the input id
      parameters:
      - description: ID of the skill to be updated
        in: path
        name: id
        required: true
        type: integer
      - description: Create skill
        in: body
        name: skill
        required: true
        schema:
          $ref: '#/definitions/models.Skill'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Skill'
      summary: Update skill identified by the given id
      tags:
      - skills
  /skills:
    get:
      consumes:
      - application/json
      description: Get details of all skills
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Skill'
            type: array
      summary: Get details of all skills
      tags:
      - skills
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user with the input paylod
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Create a new user
      tags:
      - users
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete the user corresponding to the input id
      parameters:
      - description: ID of the user to be deleted
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete user identified by the given id
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get details of user corresponding to the input id
      parameters:
      - description: ID of the user
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get details for a given user id
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update the user corresponding to the input id
      parameters:
      - description: ID of the user to be updated
        in: path
        name: id
        required: true
        type: integer
      - description: Update user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Update user identified by the given id
      tags:
      - users
  /user/address:
    post:
      consumes:
      - application/json
      description: Create a new user address with the input paylod
      parameters:
      - description: Create a user address
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.Address'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Address'
      summary: Create a new user address
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update the user address corresponding to the input id
      parameters:
      - description: Update user address
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.Address'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Address'
      summary: Update user address identified by the given id
      tags:
      - users
  /users:
    get:
      consumes:
      - application/json
      description: Get details of all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Get details of all users
      tags:
      - users
swagger: "2.0"
