definitions:
  models.Skill:
    properties:
      status:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /skill/{id}:
    get:
      consumes:
      - application/json
      description: Get details of skill corresponding to the input id
      parameters:
      - description: ID of the skill
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Skill'
      summary: Get details for a given skill id
      tags:
      - skills
  /skills:
    get:
      consumes:
      - application/json
      description: Get details of all skills
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Skill'
            type: array
      summary: Get details of all skills
      tags:
      - skills
swagger: "2.0"
